namespace TicketSystem.Classes.Enums
{
    public enum ControlsEnum
    {
        MainView = 0,
        TicketsView = 1,
        Back = 2,
        GroupCreate = 3,
        GroupDelete = 4,
        GroupEdit = 5,
        Exit = 6,
        GroupDuplicate = 7,
        GroupsView = 8,
        TicketCreate = 10,
        TicketDelete = 11,
        TicketEdit = 12,
        TicketDuplicate = 13,
        TicketHelp = 14,
        RegisterView = 20,
        ExitEntry = 21,
        UsersView = 22,
        ItemsView = 23,
        ChartsView = 24,
        UserCreate = 25,
        UserDelete = 26,
        UserEdit = 27,
        UserDuplicate = 28,
        UserWorkingTimeView = 29,
        BackToUsers = 30,
        WorkItemsPrint = 31,
        ItemCreate = 32,
        ItemDelete = 33,
        ItemEdit = 34,
        ItemDuplicate = 35,
        BackToTickets = 40,
        Magazine = 50,
        MagazineAddProduct = 51,
        MagazineDeleteProduct = 52,
        MagazineEdit = 53,
        MagazineDuplicate = 54,
        MagazineCancel = 55,
        MagazineDocuments = 56,
        MagazinePrint = 57,
        ProductCreate = 60,
        ProductDelete = 61,
        ProductEdit = 62,
        ProductDuplicate = 63,
        ProductCancel = 64,
        ProductAccept = 65,
        ProductBuy = 70,
        BarEditViewAccept = 80,
        BarEditViewCancel = 81,
        BarEditViewPrintReceipt = 82,
        BarEditViewPrintInvoice = 83
    }
}